version: '2'
services:
  web:
    build: .
    container_name: php-apache-web
    ports:
      - 8081:80
    volumes:
      - ./htdocs/:/var/www/html/
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: php-apache-mysql
    ports: 
      - 33060:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/:/var/lib/mysql/
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
  adminer:
    image: adminer
    container_name: php-adminer
    depends_on:
      - db
    ports:
      - 18081:8080
  